import pandas as pd
from pathlib import Path

# Rutas
carpeta = Path(r"C:\Users\Usuario\Desktop\UNIR\TFM\Tablas")
archivo_entrada = carpeta / "EuroStatNUEVO.csv"
carpeta_salida = carpeta  # Los CSVs de salida se guardan en la misma carpeta

# ============================================================
# DICCIONARIO DE PAÍSES
# ============================================================
dict_paises = {
    'AL': 'Albania', 'AT': 'Austria', 'BA': 'Bosnia y Herzegovina', 'BE': 'Bélgica',
    'BG': 'Bulgaria', 'CY': 'Chipre', 'CZ': 'Chequia', 'DE': 'Alemania',
    'DK': 'Dinamarca', 'EE': 'Estonia', 'EL': 'Grecia', 'ES': 'España',
    'FI': 'Finlandia', 'FR': 'Francia', 'HR': 'Croacia', 'HU': 'Hungría',
    'IE': 'Irlanda', 'IS': 'Islandia', 'IT': 'Italia', 'LI': 'Liechtenstein',
    'LT': 'Lituania', 'LU': 'Luxemburgo', 'LV': 'Letonia', 'ME': 'Montenegro',
    'MK': 'Macedonia del Norte', 'MT': 'Malta', 'NL': 'Países Bajos', 'NO': 'Noruega',
    'PL': 'Polonia', 'PT': 'Portugal', 'RO': 'Rumanía', 'RS': 'Serbia',
    'SE': 'Suecia', 'SI': 'Eslovenia', 'SK': 'Eslovaquia', 'TR': 'Turquía', 'UK': 'Reino Unido'
}

# ============================================================
# DICCIONARIO DE VARIABLES
# ============================================================
dict_variables = {
    'I_B3_12': 'Última compra online: entre 3 y 12 meses atrás',
    'I_BAPP2': 'Individuos con suscripción de pago a otras apps (últimos 3 meses) (desde 2024)',
    'I_BBMC': 'Compras online (3 meses): bicicletas, ciclomotores, coches u otros vehículos o repuestos',
    'I_BBOOK2': 'Compras online (últimos 3 meses): e-books o audiolibros como descargas (desde 2024)',
    'I_BBOOKNLG': 'Compras online (3 meses): libros impresos, revistas o periódicos',
    'I_BBOOKNLS2': 'Individuos con suscripción de pago a sitios de noticias, periódicos o revistas online (últimos 3 meses) (desde 2024)',
    'I_BCBW': 'Compras online (3 meses): productos de cosmética, belleza o bienestar',
    'I_BCG': 'Compras online (3 meses): juguetes infantiles o artículos de puericultura',
    'I_BCLOT1': 'Compras online (3 meses): ropa (incluida deportiva), calzado o accesorios',
    'I_BCPH': 'Compras online (3 meses): productos de limpieza o higiene personal',
    'I_BCS2': 'Compras online (últimos 3 meses): servicios culturales (música, películas, libros, periódicos, revistas, juegos) (desde 2024)',
    'I_BEEQU1': 'Compras online (3 meses): electrónica de consumo o electrodomésticos',
    'I_BFDR': 'Compras online (3 meses): entregas de restaurantes, cadenas de comida rápida o servicios de catering',
    'I_BFDS': 'Compras online (3 meses): alimentos o bebidas de tiendas o proveedores de kits de comida',
    'I_BFIN2': 'Compras online (3 meses): al menos una actividad financiera (acciones, seguros, préstamos)',
    'I_BFIN_CR1': 'Compras online (3 meses): préstamo, hipoteca o crédito de bancos u otros proveedores financieros',
    'I_BFIN_IN1': 'Compras online (3 meses): pólizas de seguro, incluido seguro de viaje',
    'I_BFIN_SH1': 'Compras online (3 meses): compra o venta de acciones, bonos, participaciones en fondos u otros activos financieros',
    'I_BFLMS2': 'Individuos con suscripción de pago a servicio de streaming de películas, series o deportes (últimos 3 meses) (desde 2024)',
    'I_BFURN1': 'Compras online (3 meses): muebles, accesorios para el hogar o productos de jardinería',
    'I_BGAMES2': 'Compras online (últimos 3 meses): juegos como descargas (desde 2024)',
    'I_BGAMSS': 'Individuos con suscripción de pago a servicio de streaming de videojuegos (últimos 3 meses)',
    'I_BGT3': 'Última compra online: hace más de 3 meses',
    'I_BHARD1': 'Compras online (3 meses): ordenadores, tablets, móviles o accesorios',
    'I_BHLFTS2': 'Individuos con suscripción de pago a app de salud o fitness (últimos 3 meses) (desde 2024)',
    'I_BLT12': 'Última compra online: en los últimos 12 meses',
    'I_BMED1': 'Compras online (3 meses): medicamentos o suplementos dietéticos como vitaminas',
    'I_BMUFL': 'Tipo de bienes comprados vía web o app (últimos 3 meses): música en CD, vinilo, películas o series en DVD, Blu-ray, etc.',
    'I_BMUSS2': 'Individuos con suscripción de pago a servicio de streaming de música (últimos 3 meses) (desde 2024)',
    'I_BOPG': 'Compras online (3 meses): otros bienes físicos',
    'I_BOTS': 'Compras online (3 meses): otros servicios no mencionados',
    'I_BPG_ANY': 'Compras online (3 meses): cualquier bien físico',
    'I_BRA_E': 'Compras online (3 meses) de empresas como hoteles o agencias de viajes: alojamiento alquilado',
    'I_BSIMC': 'Compras online (3 meses): suscripciones a internet o conexiones de teléfono móvil',
    'I_BSOFT2': 'Compras online (últimos 3 meses): software como descargas (desde 2024)',
    'I_BSPG': 'Compras online (3 meses): artículos deportivos (excluyendo ropa deportiva)',
    'I_BSUTIL': 'Compras online (3 meses): suscripción a electricidad, agua, calefacción, eliminación de residuos o servicios similares',
    'I_BTICK2': 'Compras online (últimos 3 meses): entradas para eventos (desde 2024)',
    'I_BTPS_E': 'Compras online (3 meses) de empresa de transporte: servicio de transporte',
    'I_BUMT12': 'Última compra online: hace más de un año',
    'I_BUMT12X': 'Última compra online: hace más de un año o nunca',
    'I_BUX': 'Última compra online: nunca',
    'I_BUY3': 'Última compra online: en los últimos 3 meses',
    'I_ECOM': 'Uso de internet: actividades de comercio electrónico',
    'I_ECO_BDS': 'Compra de dispositivo: marca, diseño o tamaño considerado importante',
    'I_ECO_DLTDIS': 'Portátil o tablet antiguo: tirado a la basura (no en recogida de residuos electrónicos)',
    'I_ECO_DLTKPT': 'Portátil o tablet antiguo: guardado en el hogar',
    'I_ECO_DLTOTH': 'Portátil o tablet antiguo: otra acción',
    'I_ECO_DLTREC': 'Portátil o tablet antiguo: reciclado',
    'I_ECO_DLTSLD': 'Portátil o tablet antiguo: vendido o regalado',
    'I_ECO_DLTUSE': 'Portátil o tablet antiguo: nunca comprado o todavía en uso',
    'I_ECO_DMOBDIS': 'Móvil o smartphone antiguo: tirado a la basura (no en recogida de residuos electrónicos)',
    'I_ECO_DMOBKPT': 'Móvil o smartphone antiguo: guardado en el hogar',
    'I_ECO_DMOBOTH': 'Móvil o smartphone antiguo: otra acción',
    'I_ECO_DMOBREC': 'Móvil o smartphone antiguo: reciclado',
    'I_ECO_DMOBSLD': 'Móvil o smartphone antiguo: vendido o regalado',
    'I_ECO_DMOBUSE': 'Móvil o smartphone antiguo: nunca comprado o todavía en uso',
    'I_ECO_DPCDIS': 'Ordenador de sobremesa antiguo: tirado a la basura (no en recogida de residuos electrónicos)',
    'I_ECO_DPCKPT': 'Ordenador de sobremesa antiguo: guardado en el hogar',
    'I_ECO_DPCOTH': 'Ordenador de sobremesa antiguo: otra acción',
    'I_ECO_DPCREC': 'Ordenador de sobremesa antiguo: reciclado',
    'I_ECO_DPCSLD': 'Ordenador de sobremesa antiguo: vendido o regalado',
    'I_ECO_DPCUSE': 'Ordenador de sobremesa antiguo: nunca comprado o todavía en uso',
    'I_ECO_PBX': 'Compra de dispositivo: nunca ha comprado móvil, smartphone, tablet u ordenador de sobremesa',
    'I_ECO_PECD': 'Compra de dispositivo: eco-diseño considerado importante',
    'I_ECO_PECO': 'Compra de dispositivo: eco-diseño, posibilidad de extender vida útil, eficiencia energética o esquema de devolución considerado importante',
    'I_ECO_PEE': 'Compra de dispositivo: eficiencia energética considerada importante',
    'I_ECO_PEG': 'Compra de dispositivo: posibilidad de extender la vida útil considerada importante',
    'I_ECO_PHD': 'Compra de dispositivo: disco duro o velocidad del procesador considerado importante',
    'I_ECO_PHDQ': 'Compra de dispositivo: solo disco duro o velocidad del procesador considerado importante',
    'I_ECO_PP': 'Compra de dispositivo: precio considerado importante',
    'I_ECO_PPQ': 'Compra de dispositivo: solo precio considerado importante',
    'I_ECO_PTBS': 'Compra de dispositivo: esquema de devolución del fabricante o vendedor considerado importante',
    'I_ECO_PX': 'Compra de dispositivo: ninguna de estas características considerada importante',
    'I_I3_12': 'Último uso de internet: entre 3 y 12 meses atrás',
    'I_IDAY': 'Frecuencia de acceso a internet: diariamente',
    'I_IGOV12FM2': 'Uso de internet: descarga o impresión de formularios oficiales (últimos 12 meses)',
    'I_IGOV12IF2': 'Uso de internet: obtención de información sobre servicios, beneficios, derechos, leyes, horarios (últimos 12 meses)',
    'I_IGOVANYS': 'Uso de internet: sitio web o app de autoridades públicas (últimos 12 meses)',
    'I_IGOVAPR': 'Uso de internet: hacer cita o reserva (últimos 12 meses)',
    'I_IGOVBE': 'Uso de internet: solicitar beneficios o derechos (últimos 12 meses)',
    'I_IGOVIDB': 'Uso de internet: acceso a bases de datos o registros públicos (últimos 12 meses)',
    'I_IGOVIP': 'Uso de internet: acceso a información personal (últimos 12 meses)',
    'I_IGOVIX': 'Uso de internet: usó internet, pero no para obtener información personal, acceder a bases de datos públicas u obtener información de webs o apps (últimos 12 meses)',
    'I_IGOVODC': 'Uso de internet: solicitar documentos oficiales o certificados (últimos 12 meses)',
    'I_IGOVPOST': 'Uso de internet: recibir comunicación o documentos oficiales (últimos 12 meses)',
    'I_IGOVR': 'Uso de internet: solicitar documentos oficiales, certificados, beneficios o derechos, o hacer otras solicitudes, reclamaciones o quejas (últimos 12 meses)',
    'I_IGOVRCC': 'Uso de internet: hacer otras solicitudes, reclamaciones o quejas (últimos 12 meses)',
    'I_IGOVRX': 'Uso de internet: no solicitó documentos oficiales, certificados, beneficios o derechos, ni hizo otras solicitudes, reclamaciones o quejas (últimos 12 meses)',
    'I_IGOVTAX2': 'Uso de internet: presentación de declaración de impuestos (últimos 12 meses) (desde 2024)',
    'I_IHIF': 'Uso de internet: búsqueda de información sobre salud',
    'I_IIGOVDU': 'Uso de internet: problema al usar web o app de autoridades públicas - difícil de usar (últimos 12 meses)',
    'I_IIGOVEID': 'Uso de internet: problema al usar web o app de autoridades públicas - problemas con firma o identificación electrónica (últimos 12 meses)',
    'I_IIGOVMOB': 'Uso de internet: problema al usar web o app de autoridades públicas - no se pudo acceder desde smartphone o tablet (últimos 12 meses)',
    'I_IIGOVOTH': 'Uso de internet: problema al usar web o app de autoridades públicas - otros problemas (últimos 12 meses)',
    'I_IIGOVPAY': 'Uso de internet: problema al usar web o app de autoridades públicas - no se pudo pagar (últimos 12 meses)',
    'I_IIGOVTP': 'Uso de internet: problema al usar web o app de autoridades públicas - problemas técnicos (últimos 12 meses)',
    'I_IIGOVX': 'Uso de internet: sin problemas al usar web o app de autoridades públicas (últimos 12 meses)',
    'I_ILT12': 'Último uso de internet: en los últimos 12 meses',
    'I_ILTWK': 'Frecuencia de acceso a internet: menos de una vez por semana',
    'I_IMT12': 'Último uso de internet: hace más de un año o nunca',
    'I_IOT_BCPP2': 'Razón para no usar sistemas IoT: preocupaciones sobre privacidad y protección de datos (últimos 3 meses) (desde 2024)',
    'I_IOT_BCSC2': 'Razón para no usar sistemas IoT: preocupaciones sobre seguridad (ej. que el dispositivo sea hackeado) (últimos 3 meses) (desde 2024)',
    'I_IOT_BCSH2': 'Razón para no usar sistemas IoT: preocupaciones sobre seguridad o salud (ej. accidente, lesión o problema de salud) (últimos 3 meses) (desde 2024)',
    'I_IOT_BCST2': 'Razón para no usar sistemas IoT: costes demasiado altos (últimos 3 meses) (desde 2024)',
    'I_IOT_BDK2': 'Razón para no usar sistemas IoT: no sabía que existían tales dispositivos o sistemas (últimos 3 meses) (desde 2024)',
    'I_IOT_BLC2': 'Razón para no usar sistemas IoT: falta de compatibilidad con otros dispositivos o sistemas (últimos 3 meses) (desde 2024)',
    'I_IOT_BLSK2': 'Razón para no usar sistemas IoT: falta de habilidades para usar esos dispositivos o sistemas (últimos 3 meses) (desde 2024)',
    'I_IOT_BNN2': 'Razón para no usar sistemas IoT: no necesita usar esos dispositivos/sistemas conectados (últimos 3 meses) (desde 2024)',
    'I_IOT_BOTH2': 'Razón para no usar sistemas IoT: otras razones (últimos 3 meses) (desde 2024)',
    'I_IOT_DCAR2': 'Individuos que usaron coche con conexión a internet incorporada (últimos 3 meses) (desde 2024)',
    'I_IOT_DCS2': 'Individuos que usaron dispositivo vestible conectado a internet (ej. smartwatch, pulsera fitness) (últimos 3 meses) (desde 2024)',
    'I_IOT_DEM2': 'Individuos que usaron sistema de gestión energética del hogar conectado a internet (ej. termostato, contadores, luces) (últimos 3 meses) (desde 2024)',
    'I_IOT_DHA2': 'Individuos que usaron electrodoméstico conectado a internet (ej. robot aspirador, nevera, horno, cafetera) (últimos 3 meses) (desde 2024)',
    'I_IOT_DHE2': 'Individuos que usaron dispositivo conectado a internet para salud y cuidado médico (ej. monitorizar presión arterial, nivel de azúcar, peso) (últimos 3 meses) (desde 2024)',
    'I_IOT_DOM2': 'Individuos que usaron sistema doméstico conectado a internet (gestión energética, seguridad, electrodomésticos o asistente virtual) (últimos 3 meses)',
    'I_IOT_DSEC2': 'Individuos que usaron sistema de seguridad del hogar conectado a internet (ej. alarma, detector de humo, cámaras, cerraduras) (últimos 3 meses) (desde 2024)',
    'I_IOT_DTOY2': 'Individuos que usaron juguete conectado a internet (ej. robots, drones, muñecas) (últimos 3 meses) (desde 2024)',
    'I_IOT_DVA2': 'Individuos que usaron asistente virtual conectado a internet como altavoz inteligente o app (últimos 3 meses) (desde 2024)',
    'I_IOT_DX2': 'Individuos que no usaron ningún sistema doméstico conectado a internet ni asistentes virtuales (últimos 3 meses) (desde 2024)',
    'I_IOT_IUANY2': 'Individuos que usaron solución de entretenimiento doméstico conectada a internet (ej. TV, consola, sistema de audio, altavoces inteligentes) (últimos 3 meses) (desde 2024)',
    'I_IOT_IUGC2': 'Individuos que usaron consola de videojuegos conectada a internet (últimos 3 meses) (desde 2024)',
    'I_IOT_IUHA2': 'Individuos que usaron sistema de audio doméstico o altavoces inteligentes conectados a internet (últimos 3 meses) (desde 2024)',
    'I_IOT_IUTV2': 'Individuos que usaron TV conectada a internet (últimos 3 meses) (desde 2024)',
    'I_IOT_PDU2': 'Individuos que usaron IoT y encontraron dificultades de uso (últimos 3 meses) (desde 2024)',
    'I_IOT_POTH2': 'Individuos que usaron IoT y encontraron otros problemas (últimos 3 meses) (desde 2024)',
    'I_IOT_PSEC2': 'Individuos que usaron IoT y encontraron problemas de seguridad o privacidad (últimos 3 meses) (desde 2024)',
    'I_IOT_PSHE2': 'Individuos que usaron IoT y encontraron problemas de seguridad o salud (últimos 3 meses) (desde 2024)',
    'I_IOT_PX2': 'Individuos que usaron IoT y no encontraron ningún problema (últimos 3 meses) (desde 2024)',
    'I_IOT_USE2': 'Individuos que usaron dispositivos conectados a internet (IoT) para fines privados (últimos 3 meses) (desde 2024)',
    'I_IRGOVEID': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - por falta de firma electrónica (últimos 12 meses)',
    'I_IRGOVLS': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - por falta de habilidades o conocimientos (últimos 12 meses)',
    'I_IRGOVNAP': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - porque no había servicio online disponible (últimos 12 meses)',
    'I_IRGOVNN': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - porque no lo necesitaba (últimos 12 meses)',
    'I_IRGOVNNX': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - aunque lo necesitaba (últimos 12 meses)',
    'I_IRGOVOP': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - porque otra persona lo hizo (últimos 12 meses)',
    'I_IRGOVOTH': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - por otras razones (últimos 12 meses)',
    'I_IRGOVSEC': 'Uso de internet: no solicitó documento oficial ni hizo reclamación - por preocupaciones de seguridad (últimos 12 meses)',
    'I_IU3': 'Último uso de internet: en los últimos 3 meses',
    'I_IUACDL': 'Individuos que intentaron eliminar (o cerrar) una cuenta de app o servicio gratuito',
    'I_IUACDLP': 'Individuos que encontraron problemas al eliminar cuenta de app o servicio gratuito',
    'I_IUACRG': 'Individuos que abrieron cuenta o se registraron en app o servicio gratuito',
    'I_IUAPR': 'Uso de internet: acceso a registros de salud personales online',
    'I_IUBK': 'Uso de internet: banca por internet',
    'I_IUCHAT1': 'Uso de internet: mensajería instantánea (ej. Skype, Messenger, WhatsApp, Viber)',
    'I_IUCPP': 'Uso de internet: participación cívica o política',
    'I_IUEM': 'Uso de internet: envío/recepción de correos electrónicos',
    'I_IUEVR': 'Individuos que alguna vez han usado internet',
    'I_IUGOV1': 'Uso de internet: interacción con autoridades públicas (últimos 12 meses)',
    'I_IUGOV1X': 'Uso de internet: usó internet, pero no para interacción con autoridades públicas (últimos 12 meses)',
    'I_IUGOV1_IGOVR': 'Uso de internet: acceso a información y realización de solicitudes o reclamaciones online (últimos 12 meses)',
    'I_IUIF': 'Uso de internet: búsqueda de información sobre bienes y servicios',
    'I_IUMAPP': 'Uso de internet: hacer cita con profesional médico vía web',
    'I_IUMT12': 'Último uso de internet: hace más de un año',
    'I_IUMUSS1': 'Uso de internet: escuchar música (ej. radio web, streaming de música) o descargar música',
    'I_IUNW1': 'Uso de internet: leer sitios de noticias online/periódicos/revistas de noticias',
    'I_IUOANY': 'Uso de internet: cualquiera de las actividades de aprendizaje (i_iuolc, i_iuolm, i_iuocis)',
    'I_IUOCIS1': 'Uso de internet: comunicación con instructores o estudiantes usando herramientas de audio o video online (ej. Zoom, MS Teams, Google Classroom) (últimos 3 meses)',
    'I_IUOFE': 'Uso de internet: participación en actividades de aprendizaje para educación formal (ej. escuela o universidad) (últimos 3 meses)',
    'I_IUOHC': 'Uso de internet: para otros servicios de salud vía web o app en lugar de ir al hospital o visitar al médico',
    'I_IUOLANY': 'Uso de internet: hacer curso online (de cualquier tema) o usar material de aprendizaje online',
    'I_IUOLC': 'Uso de internet: hacer curso online (de cualquier tema)',
    'I_IUOLM': 'Uso de internet: material de aprendizaje online',
    'I_IUOPP': 'Uso de internet: participación en actividades de aprendizaje para fines personales (últimos 3 meses)',
    'I_IUOW': 'Uso de internet: participación en actividades de aprendizaje para fines profesionales/laborales (últimos 3 meses)',
    'I_IUPCAST': 'Uso de internet: escuchar o descargar podcasts (últimos 3 meses)',
    'I_IUPDG': 'Uso de internet: jugar o descargar juegos',
    'I_IUPH1': 'Uso de internet: llamadas telefónicas o videollamadas',
    'I_IUPHCHAT1': 'Uso de internet: llamadas telefónicas o videollamadas, o mensajería instantánea (ej. Skype, Messenger, WhatsApp, Viber)',
    'I_IUPOL2': 'Uso de internet: expresar opiniones sobre temas cívicos o políticos en webs o redes sociales (ej. Facebook, Twitter, Instagram, YouTube)',
    'I_IUSE': 'Frecuencia de acceso a internet: una vez por semana (incluido todos los días)',
    'I_IUSELL': 'Uso de internet: venta de bienes o servicios',
    'I_IUSNET': 'Uso de internet: participación en redes sociales (crear perfil, publicar mensajes u otras contribuciones en Facebook, Twitter, etc.)',
    'I_IUSTV': 'Uso de internet: ver TV en streaming por internet (en directo o a la carta) de emisoras de TV',
    'I_IUSTVV': 'Uso de internet: ver TV o videos en streaming por internet',
    'I_IUV': 'Uso de internet: ver contenido de video de servicios comerciales o de compartición',
    'I_IUVOD': 'Uso de internet: ver video bajo demanda de servicios comerciales',
    'I_IUVOTE': 'Uso de internet: participar en consultas online o votaciones para definir temas cívicos o políticos (ej. planificación urbana, firmar petición)',
    'I_IUVSS': 'Uso de internet: ver contenido de video de servicios de compartición',
    'I_IUX': 'Uso de internet: nunca',
    'I_IWK': 'Frecuencia de acceso a internet: al menos una vez por semana (pero no todos los días)',
    'h_iacc': 'Algún miembro del hogar tiene acceso a internet en casa',
    'h_iaccx': 'Ningún miembro del hogar tiene acceso a internet en casa',
    'h_iaccz': 'No sabe si algún miembro del hogar tiene acceso a internet en casa',
    'i_bgt3_iu3': 'Usé internet en los últimos 3 meses y compré bienes o servicios online hace más de 3 meses',
    'i_bhlfts_iot_dhe2': 'En los últimos 3 meses, compré apps de salud o fitness y usé dispositivos conectados para monitorizar presión arterial, azúcar, peso corporal',
    'i_botsx': 'No compré otros servicios que los mencionados vía web o app en los últimos 3 meses',
    'i_eco_drecsld': 'Reciclé, vendí o regalé mi equipo TIC en desuso: móvil, smartphone, portátil, tablet u ordenador de sobremesa',
    'i_eco_pge2v2': 'Al comprar mi dispositivo más reciente, consideré al menos 2 características como importantes',
    'i_eco_pge3v2': 'Al comprar mi dispositivo más reciente, consideré al menos 3 características como importantes',
    'i_eco_pge4v2': 'Al comprar mi dispositivo más reciente, consideré al menos 4 características como importantes',
    'i_iday1': 'En los últimos 3 meses, accedí a internet, en promedio, una vez al día o casi todos los días',
    'i_iday_d': 'En los últimos 3 meses, accedí a internet, en promedio, varias veces al día',
    'i_igovusehi': 'Alta intensidad de uso de diferentes servicios de e-gobierno',
    'i_igovuselo': 'Baja intensidad de uso de diferentes servicios de e-gobierno',
    'i_ihif_bhlfts2': 'Usé internet en los últimos 3 meses para buscar información de salud y compré apps de salud o fitness',
    'i_ihif_bmed1': 'En los últimos 3 meses, usé internet para buscar información de salud y compré medicamentos o suplementos dietéticos',
    'i_ihif_iot_bcsh2': 'Usé internet en los últimos 3 meses para buscar información de salud y no usé dispositivos IoT por preocupaciones de seguridad o salud',
    'i_ihif_iot_bcsh2x': 'Usé internet en los últimos 3 meses para buscar información de salud y no usé dispositivos IoT, pero no por preocupaciones de seguridad o salud',
    'i_ihif_iot_dhe2': 'Usé internet en los últimos 3 meses para buscar información de salud y usé dispositivos conectados para monitorizar presión arterial, azúcar, peso',
    'i_iltwkpop': 'Todos los individuos que acceden a internet menos de una vez por semana o no accedieron en los últimos 3 meses',
    'i_iot_bcsh2x': 'Una razón para no usar dispositivos IoT no fue: Preocupaciones sobre seguridad o salud',
    'i_iot_bdk2x': 'La razón para no usar dispositivos IoT no fue: No sabía que existían tales dispositivos',
    'i_iupol2_iday': 'En los últimos 3 meses, accedí a internet diariamente y expresé opiniones sobre temas cívicos o políticos en webs o redes sociales',
    'i_iupol2_iday1': 'En los últimos 3 meses, accedí a internet una vez al día y expresé opiniones sobre temas cívicos o políticos en webs o redes sociales',
    'i_iupol2_iday_d': 'En los últimos 3 meses, accedí a internet varias veces al día y expresé opiniones sobre temas cívicos o políticos en webs o redes sociales',
    'i_iupol2_iltwk': 'En los últimos 3 meses, accedí a internet menos de una vez por semana y expresé opiniones sobre temas cívicos o políticos en webs o redes sociales',
    'i_iupol2_iuse': 'En los últimos 3 meses, accedí a internet al menos una vez por semana y expresé opiniones sobre temas cívicos o políticos en webs o redes sociales',
    'i_iupol2_iwk': 'En los últimos 3 meses, accedí a internet al menos una vez por semana (no diario) y expresé opiniones sobre temas cívicos o políticos en webs o redes sociales',
    'i_iusnet_cpp': 'Usé internet en los últimos 3 meses para participar en redes sociales y para participación cívica o política',
    'sampleh': 'Tamaño de muestra para hogares',
    'samplep': 'Tamaño de muestra para individuos'
}

# ============================================================
# DICCIONARIO DE DESAGREGACIONES
# ============================================================
dict_desagregaciones = {
    'A1': 'Persona sola',
    'A1_DCH': 'Persona sola con hijos dependientes',
    'A2': 'Dos adultos',
    'A2_DCH': 'Dos adultos con hijos dependientes',
    'A_GE3': 'Tres o más adultos',
    'A_GE3_DCH': 'Tres o más adultos con hijos dependientes',
    'ALL_DCH': 'Todos los tipos con hijos dependientes',
    'ALL_NDCH': 'Todos los tipos sin hijos dependientes',
    'TOTAL': 'Total',
    # Regiones Austria
    'AT1': 'Austria Oriental',
    'AT11': 'Burgenland',
    'AT12': 'Baja Austria',
    'AT13': 'Viena',
    'AT2': 'Austria Meridional',
    'AT21': 'Carintia',
    'AT22': 'Estiria',
    'AT3': 'Austria Occidental',
    'AT31': 'Alta Austria',
    'AT32': 'Salzburgo',
    'AT33': 'Tirol',
    'AT34': 'Vorarlberg',
    # Regiones Bélgica
    'BE1': 'Región de Bruselas-Capital',
    'BE10': 'Región de Bruselas-Capital',
    'BE2': 'Región Flamenca',
    'BE21': 'Amberes',
    'BE22': 'Limburgo',
    'BE23': 'Flandes Oriental',
    'BE24': 'Brabante Flamenco',
    'BE25': 'Flandes Occidental',
    'BE3': 'Región Valona',
    'BE31': 'Brabante Valón',
    'BE32': 'Henao',
    'BE33': 'Lieja',
    'BE34': 'Luxemburgo (BE)',
    'BE35': 'Namur',
    # Regiones Bulgaria
    'BG3': 'Bulgaria Septentrional y Sudoriental',
    'BG31': 'Noroeste',
    'BG32': 'Norte Central',
    'BG33': 'Noreste',
    'BG34': 'Sudeste',
    'BG4': 'Bulgaria Sudoccidental y Sur Central',
    'BG41': 'Suroeste',
    'BG42': 'Sur Central',
    # Chipre
    'CY0': 'Chipre',
    'CY00': 'Chipre',
    # Chequia
    'CZ0': 'Chequia',
    'CZ01': 'Praga',
    'CZ02': 'Bohemia Central',
    'CZ03': 'Suroeste',
    'CZ04': 'Noroeste',
    'CZ05': 'Noreste',
    'CZ06': 'Sudeste',
    'CZ07': 'Moravia Central',
    'CZ08': 'Moravia-Silesia',
    # Regiones Alemania
    'DE1': 'Baden-Wurtemberg',
    'DE2': 'Baviera',
    'DE3': 'Berlín',
    'DE4': 'Brandeburgo',
    'DE5': 'Bremen',
    'DE6': 'Hamburgo',
    'DE7': 'Hesse',
    'DE8': 'Mecklemburgo-Pomerania Occidental',
    'DE9': 'Baja Sajonia',
    'DEA': 'Renania del Norte-Westfalia',
    'DEB': 'Renania-Palatinado',
    'DEC': 'Sarre',
    'DED': 'Sajonia',
    'DEE': 'Sajonia-Anhalt',
    'DEF': 'Schleswig-Holstein',
    'DEG': 'Turingia',
    # Dinamarca
    'DK0': 'Dinamarca',
    'DK01': 'Capital',
    'DK02': 'Selandia',
    'DK03': 'Dinamarca Meridional',
    'DK04': 'Jutlandia Central',
    'DK05': 'Jutlandia Septentrional',
    # Estonia
    'EE0': 'Estonia',
    'EE00': 'Estonia',
    # Regiones España
    'ES1': 'Noroeste',
    'ES11': 'Galicia',
    'ES12': 'Principado de Asturias',
    'ES13': 'Cantabria',
    'ES2': 'Noreste',
    'ES21': 'País Vasco',
    'ES22': 'Comunidad Foral de Navarra',
    'ES23': 'La Rioja',
    'ES24': 'Aragón',
    'ES3': 'Comunidad de Madrid',
    'ES30': 'Comunidad de Madrid',
    'ES4': 'Centro (ES)',
    'ES41': 'Castilla y León',
    'ES42': 'Castilla-La Mancha',
    'ES43': 'Extremadura',
    'ES5': 'Este',
    'ES51': 'Cataluña',
    'ES52': 'Comunitat Valenciana',
    'ES53': 'Illes Balears',
    'ES6': 'Sur',
    'ES61': 'Andalucía',
    'ES62': 'Región de Murcia',
    'ES63': 'Ciudad de Ceuta',
    'ES64': 'Ciudad de Melilla',
    'ES7': 'Canarias',
    'ES70': 'Canarias',
    # Finlandia
    'FI1': 'Finlandia Continental',
    'FI19': 'Finlandia Occidental',
    'FI1B': 'Helsinki-Uusimaa',
    'FI1C': 'Finlandia Meridional',
    'FI1D': 'Finlandia Septentrional y Oriental',
    # Francia
    'FR1': 'Île de France',
    'FR10': 'Île de France',
    'FRB': 'Centro - Valle del Loira',
    'FRB0': 'Centro - Valle del Loira',
    'FRC': 'Borgoña-Franco Condado',
    'FRC1': 'Borgoña',
    'FRC2': 'Franco Condado',
    'FRD': 'Amigos',
    'FRD1': 'Baja Normandía',
    'FRD2': 'Alta Normandía',
    'FRE': 'Altos de Francia',
    'FRE1': 'Norte-Paso de Calais',
    'FRE2': 'Picardía',
    'FRF': 'Gran Este',
    'FRF1': 'Alsacia',
    'FRF2': 'Champaña-Ardenas',
    'FRF3': 'Lorena',
    'FRG': 'Países del Loira',
    'FRG0': 'Países del Loira',
    'FRH': 'Bretaña',
    'FRH0': 'Bretaña',
    'FRI': 'Nueva Aquitania',
    'FRI1': 'Aquitania',
    'FRI2': 'Lemosín',
    'FRI3': 'Poitou-Charentes',
    'FRJ': 'Occitania',
    'FRJ1': 'Languedoc-Rosellón',
    'FRJ2': 'Mediodía-Pirineos',
    'FRK': 'Auvernia-Ródano-Alpes',
    'FRK1': 'Auvernia',
    'FRK2': 'Ródano-Alpes',
    'FRL': 'Provenza-Alpes-Costa Azul',
    'FRL0': 'Provenza-Alpes-Costa Azul',
    'FRM': 'Córcega',
    'FRM0': 'Córcega',
    'FRY': 'Regiones Ultraperiféricas Francesas',
    'FRY1': 'Guadalupe',
    'FRY2': 'Martinica',
    'FRY3': 'Guayana Francesa',
    'FRY4': 'Reunión',
    # Croacia
    'HR0': 'Croacia',
    'HR03': 'Croacia Adriática',
    'HR05': 'Ciudad de Zagreb',
    'HR06': 'Croacia Septentrional',
    # Hungría
    'HU1': 'Hungría Central',
    'HU11': 'Budapest',
    'HU12': 'Pest',
    'HU2': 'Transdanubia',
    'HU21': 'Transdanubia Central',
    'HU22': 'Transdanubia Occidental',
    'HU23': 'Transdanubia Meridional',
    'HU3': 'Gran Llanura y Norte',
    'HU31': 'Hungría Septentrional',
    'HU32': 'Gran Llanura Septentrional',
    'HU33': 'Gran Llanura Meridional',
    # Italia
    'ITC': 'Noroeste',
    'ITC1': 'Piamonte',
    'ITC2': 'Valle de Aosta',
    'ITC3': 'Liguria',
    'ITC4': 'Lombardía',
    'ITF': 'Sur',
    'ITF1': 'Abruzos',
    'ITF2': 'Molise',
    'ITF3': 'Campania',
    'ITF4': 'Apulia',
    'ITF5': 'Basilicata',
    'ITF6': 'Calabria',
    'ITG': 'Islas',
    'ITG1': 'Sicilia',
    'ITG2': 'Cerdeña',
    'ITH': 'Noreste',
    'ITH1': 'Provincia Autónoma de Bolzano',
    'ITH2': 'Provincia Autónoma de Trento',
    'ITH3': 'Véneto',
    'ITH4': 'Friuli-Venecia Julia',
    'ITH5': 'Emilia-Romaña',
    'ITI': 'Centro (IT)',
    'ITI1': 'Toscana',
    'ITI2': 'Umbría',
    'ITI3': 'Marcas',
    'ITI4': 'Lacio',
    # Lituania
    'LT0': 'Lituania',
    'LT01': 'Lituania Capital',
    'LT02': 'Lituania Central y Occidental',
    # País de nacimiento y nacionalidad
    'CB_EU_FOR': 'Individuos nacidos en otro Estado miembro de la UE',
    'CB_EXT_EU': 'Individuos nacidos en país no perteneciente a la UE',
    'CB_FOR': 'Individuos nacidos en el extranjero',
    'CB_NAT': 'Individuos nacidos en el país',
    'CC_EU_FOR': 'Nacionales de otro Estado miembro de la UE',
    'CC_EXT_EU': 'Nacionales de país no perteneciente a la UE',
    'CC_FOR': 'No nacionales',
    'CC_NAT': 'Nacionales',
    'cb_cc_eu_for': 'Individuos nacidos en otro Estado miembro de la UE y nacionales de otro Estado miembro de la UE',
    'cb_cc_ext_eu': 'Individuos nacidos en país no perteneciente a la UE y nacionales de país no perteneciente a la UE',
    'cb_cc_for': 'Individuos nacidos en el extranjero y no nacionales',
    # Discapacidad
    'DIS_LTD': 'Discapacidad (limitación de actividad) - limitado, pero no severamente',
    'DIS_LTD_SEV': 'Discapacidad (limitación de actividad) - limitado o severamente limitado',
    'DIS_NONE': 'Discapacidad (limitación de actividad) - sin limitación',
    'DIS_SEV': 'Discapacidad (limitación de actividad) - severamente limitado',
    'F_DIS_LTD': 'Mujeres con discapacidad (limitación de actividad) - limitada, pero no severamente',
    'F_DIS_LTD_SEV': 'Mujeres con discapacidad (limitación de actividad) - limitada o severamente limitada',
    'F_DIS_NONE': 'Mujeres con discapacidad (limitación de actividad) - sin limitación',
    'F_DIS_SEV': 'Mujeres con discapacidad (limitación de actividad) - severamente limitada',
    'M_DIS_LTD': 'Hombres con discapacidad (limitación de actividad) - limitado, pero no severamente',
    'M_DIS_LTD_SEV': 'Hombres con discapacidad (limitación de actividad) - limitado o severamente limitado',
    'M_DIS_NONE': 'Hombres con discapacidad (limitación de actividad) - sin limitación',
    'M_DIS_SEV': 'Hombres con discapacidad (limitación de actividad) - severamente limitado',
    # Empleo
    'EMPL_UNE': 'Individuos en la fuerza laboral (empleados y desempleados)',
    'EMP_A': 'Personas de 16-74 años trabajando en agricultura, silvicultura o pesca',
    'EMP_B': 'Personas de 16-74 años trabajando en minería o canteras',
    'EMP_C': 'Personas de 16-74 años trabajando en manufactura',
    'EMP_CON_PRM': 'Trabajando con empleo permanente o contrato de duración indefinida',
    'EMP_CON_TMP': 'Trabajando con empleo temporal o contrato de duración limitada',
    'EMP_D': 'Personas de 16-74 años trabajando en suministro de electricidad, gas, vapor o aire acondicionado',
    'EMP_E': 'Personas de 16-74 años trabajando en suministro de agua; alcantarillado, gestión de residuos',
    'EMP_F': 'Personas de 16-74 años trabajando en construcción',
    'EMP_G': 'Personas de 16-74 años trabajando en comercio mayorista o minorista, reparación de vehículos',
    'EMP_H': 'Personas de 16-74 años trabajando en transporte y almacenamiento',
    'EMP_I': 'Personas de 16-74 años trabajando en hostelería',
    'EMP_J': 'Personas de 16-74 años trabajando en información y comunicación',
    'EMP_K': 'Personas de 16-74 años trabajando en actividades financieras o de seguros',
    'EMP_L': 'Personas de 16-74 años trabajando en actividades inmobiliarias',
    'EMP_M': 'Personas de 16-74 años trabajando en actividades profesionales, científicas o técnicas',
    'EMP_N': 'Personas de 16-74 años trabajando en actividades administrativas o de servicios de apoyo',
    'EMP_O': 'Personas de 16-74 años trabajando en administración pública, defensa o seguridad social obligatoria',
    'EMP_P': 'Personas de 16-74 años trabajando en educación',
    'EMP_Q': 'Personas de 16-74 años trabajando en sanidad o servicios sociales',
    'EMP_R': 'Personas de 16-74 años trabajando en arte, entretenimiento o recreación',
    'EMP_S': 'Personas de 16-74 años trabajando en otras actividades de servicios',
    'EMP_WKT_FT': 'Empleados trabajando a tiempo completo',
    'EMP_WKT_PT': 'Empleados trabajando a tiempo parcial',
    'SAL': 'Empleados',
    'SAL_SELF_FAM': 'Empleados, autónomos, trabajadores familiares',
    'SELF_FAM': 'Autónomos, trabajadores familiares',
    'SELF_NS': 'Autónomos sin empleados',
    'SELF_S': 'Autónomos con empleados',
    'STUD': 'Estudiantes',
    'UNE': 'Desempleados',
    'RETIR_OTHER': 'Individuos jubilados o fuera de la fuerza laboral (excluyendo estudiantes)',
    # Educación
    'I0_2': 'Individuos sin educación formal o con educación baja',
    'I3_4': 'Individuos con educación formal media',
    'I5_8': 'Individuos con educación formal alta',
    'F_I0_2': 'Mujeres con educación formal baja',
    'F_I3_4': 'Mujeres con educación formal media',
    'F_I5_8': 'Mujeres con educación formal alta',
    'M_I0_2': 'Hombres con educación formal baja',
    'M_I3_4': 'Hombres con educación formal media',
    'M_I5_8': 'Hombres con educación formal alta',
    'i0': 'Menos de educación primaria',
    'i1': 'Educación primaria',
    'i2': 'Educación secundaria inferior',
    'i3': 'Educación secundaria superior',
    'i4': 'Educación postsecundaria pero no terciaria',
    'i5_2011': 'Educación terciaria de ciclo corto',
    'i6_2011': 'Grado o equivalente',
    'i7_2011': 'Máster o equivalente',
    'i8_2011': 'Doctorado o equivalente',
    # Edad y género
    'Y16_17': 'Individuos de 16 a 17 años',
    'Y16_19': 'Individuos de 16 a 19 años',
    'Y16_24': 'Individuos de 16 a 24 años',
    'Y16_29': 'Individuos de 16 a 29 años',
    'Y20_24': 'Individuos de 20 a 24 años',
    'Y25_29': 'Individuos de 25 a 29 años',
    'Y25_34': 'Individuos de 25 a 34 años',
    'Y25_54': 'Individuos de 25 a 54 años',
    'Y25_64': 'Individuos de 25 a 64 años',
    'Y35_44': 'Individuos de 35 a 44 años',
    'Y45_54': 'Individuos de 45 a 54 años',
    'Y55_64': 'Individuos de 55 a 64 años',
    'Y55_74': 'Individuos de 55 a 74 años',
    'Y65_74': 'Individuos de 65 a 74 años',
    'Y75_MAX': 'Individuos de 75 años o más',
    'F_Y16_19': 'Mujeres de 16 a 19 años',
    'F_Y16_24': 'Mujeres de 16 a 24 años',
    'F_Y16_29': 'Mujeres de 16 a 29 años',
    'F_Y16_74': 'Mujeres de 16 a 74 años',
    'F_Y20_24': 'Mujeres de 20 a 24 años',
    'F_Y25_29': 'Mujeres de 25 a 29 años',
    'F_Y25_34': 'Mujeres de 25 a 34 años',
    'F_Y25_54': 'Mujeres de 25 a 54 años',
    'F_Y25_64': 'Mujeres de 25 a 64 años',
    'F_Y35_44': 'Mujeres de 35 a 44 años',
    'F_Y45_54': 'Mujeres de 45 a 54 años',
    'F_Y55_64': 'Mujeres de 55 a 64 años',
    'F_Y55_74': 'Mujeres de 55 a 74 años',
    'F_Y65_74': 'Mujeres de 65 a 74 años',
    'M_Y16_19': 'Hombres de 16 a 19 años',
    'M_Y16_24': 'Hombres de 16 a 24 años',
    'M_Y16_29': 'Hombres de 16 a 29 años',
    'M_Y16_74': 'Hombres de 16 a 74 años',
    'M_Y20_24': 'Hombres de 20 a 24 años',
    'M_Y25_29': 'Hombres de 25 a 29 años',
    'M_Y25_34': 'Hombres de 25 a 34 años',
    'M_Y25_54': 'Hombres de 25 a 54 años',
    'M_Y25_64': 'Hombres de 25 a 64 años',
    'M_Y35_44': 'Hombres de 35 a 44 años',
    'M_Y45_54': 'Hombres de 45 a 54 años',
    'M_Y55_64': 'Hombres de 55 a 64 años',
    'M_Y55_74': 'Hombres de 55 a 74 años',
    'M_Y65_74': 'Hombres de 65 a 74 años',
    # Combinaciones edad-educación
    'Y16_24HI': 'Individuos de 16-24 años con educación formal alta',
    'Y16_24LO': 'Individuos de 16-24 años con educación baja',
    'Y16_24ME': 'Individuos de 16-24 años con educación formal media',
    'Y16_29HI': 'Individuos de 16-29 años con educación formal alta',
    'Y16_29LO': 'Individuos de 16-29 años con educación formal baja',
    'Y16_29ME': 'Individuos de 16-29 años con educación formal media',
    'Y25_54HI': 'Individuos de 25-54 años con educación formal alta',
    'Y25_54LO': 'Individuos de 25-54 años con educación formal baja',
    'Y25_54ME': 'Individuos de 25-54 años con educación formal media',
    'Y25_64HI': 'Individuos de 25-64 años con educación formal alta',
    'Y25_64LO': 'Individuos de 25-64 años con educación formal baja',
    'Y25_64ME': 'Individuos de 25-64 años con educación formal media',
    'Y55_74HI': 'Individuos de 55-74 años con educación formal alta',
    'Y55_74LO': 'Individuos de 55-74 años con educación formal baja',
    'Y55_74ME': 'Individuos de 55-74 años con educación formal media',
    # Combinaciones edad-discapacidad
    'Y16_24_DIS_LTD': 'Individuos de 16-24 años con discapacidad - limitado, pero no severamente',
    'Y16_24_DIS_LTD_SEV': 'Individuos de 16-24 años con discapacidad - limitado o severamente limitado',
    'Y16_24_DIS_NONE': 'Individuos de 16-24 años con discapacidad - sin limitación',
    'Y16_24_DIS_SEV': 'Individuos de 16-24 años con discapacidad - severamente limitado',
    'Y25_54_DIS_LTD': 'Individuos de 25-54 años con discapacidad - limitado, pero no severamente',
    'Y25_54_DIS_LTD_SEV': 'Individuos de 25-54 años con discapacidad - limitado o severamente limitado',
    'Y25_54_DIS_NONE': 'Individuos de 25-54 años con discapacidad - sin limitación',
    'Y25_54_DIS_SEV': 'Individuos de 25-54 años con discapacidad - severamente limitado',
    'Y55_74_DIS_LTD': 'Individuos de 55-74 años con discapacidad - limitado, pero no severamente',
    'Y55_74_DIS_LTD_SEV': 'Individuos de 55-74 años con discapacidad - limitado o severamente limitado',
    'Y55_74_DIS_NONE': 'Individuos de 55-74 años con discapacidad - sin limitación',
    'Y55_74_DIS_SEV': 'Individuos de 55-74 años con discapacidad - severamente limitado',
    # Combinaciones edad-empleo
    'Y25_64_EMPL_UNE': 'Individuos de 25-64 años en la fuerza laboral (empleados y desempleados)',
    'Y25_64_RETIROTH': 'Individuos de 25-64 años jubilados o fuera de la fuerza laboral (excluyendo estudiantes)',
    'Y25_64_SALSELFFAM': 'Individuos de 25-64 años que son empleados, autónomos o trabajadores familiares',
    'Y25_64_UNE': 'Individuos de 25-64 años desempleados',
    # Hogares e individuos
    'IND_DCH': 'Individuos viviendo en hogar con hijos',
    'IND_DEG1': 'Individuos viviendo en ciudades',
    'IND_DEG2': 'Individuos viviendo en pueblos y suburbios',
    'IND_DEG3': 'Individuos viviendo en áreas rurales',
    'IND_NO_DCH': 'Individuos viviendo en hogar sin hijos',
    'IND_TOTAL': 'Todos los individuos',
    'HH_DEG1': 'Hogares ubicados en ciudades',
    'HH_DEG2': 'Hogares ubicados en pueblos y suburbios',
    'HH_DEG3': 'Hogares ubicados en áreas rurales',
    # Ocupación
    'ISCO0_5': 'No manual incluyendo fuerzas armadas',
    'ISCO6_9': 'Manual',
    'ISCO_ICT': 'Profesionales TIC',
    'ISCO_ICTX': 'Profesionales no TIC',
    # Ingresos
    'hi_q5_1': 'Ingresos en el primer quintil, es decir, entre el 20% de ingresos más bajos',
    'hi_q5_2': 'Ingresos en el segundo quintil, es decir, entre el 40% de ingresos más bajos pero no entre el 20% más bajo',
    'hi_q5_3': 'Ingresos en el tercer quintil, es decir, entre el 60% de ingresos más bajos pero no entre el 40% más bajo',
    'hi_q5_4': 'Ingresos en el cuarto quintil, es decir, entre el 80% de ingresos más bajos pero no entre el 60% más bajo',
    'hi_q5_5': 'Ingresos en el quinto quintil, es decir, entre el 20% de ingresos más altos',
    # Desarrollo regional
    'hh_dev_l': 'Hogares en regiones menos desarrolladas',
    'hh_dev_m': 'Hogares en regiones más desarrolladas',
    'hh_dev_t': 'Hogares en regiones en transición',
    'ind_dev_l': 'Viviendo en regiones menos desarrolladas',
    'ind_dev_m': 'Viviendo en regiones más desarrolladas',
    'ind_dev_t': 'Viviendo en regiones en transición',
    'ind_disabl': 'Individuos incapaces de trabajar debido a problemas de salud de larga duración',
    # Factores de riesgo
    'RF_GE1': 'Individuos con al menos 1 de 3 características: 55-74 años; educación baja; desempleado o inactivo o jubilado',
    'RF_GE2': 'Individuos con al menos 2 de 3 características: 55-74 años; educación baja; desempleado o inactivo o jubilado',
    'rf_0': 'Individuo sin factor de riesgo',
    'rf_3': 'Individuo con tres factores de riesgo',
    'rf_blank': 'Individuo para el que no se pudieron determinar los factores de riesgo',
    # Otros
    'FAM': 'Familia y parientes',
    'FRD': 'Amigos'
}

# ============================================================
# DICCIONARIO DE UNIDADES
# ============================================================
dict_unidades = {
    'PC_HH': 'Porcentaje de hogares',
    'PC_IND': 'Porcentaje de individuos',
    'PC_IND_BUY3': 'Porcentaje de individuos que compraron online en los últimos 3 meses',
    'PC_IND_ILT12': 'Porcentaje de individuos que usaron internet en el último año',
    'PC_IND_IOT_DX2': 'Porcentaje de individuos que no han usado dispositivos o sistemas IoT en los últimos 3 meses',
    'PC_IND_IOT_USE2': 'Porcentaje de individuos que han usado dispositivos o sistemas IoT en los últimos 3 meses',
    'PC_IND_IU3': 'Porcentaje de individuos que usaron internet en los últimos 3 meses',
    'PC_IND_IUACDL': 'Porcentaje de individuos que han intentado eliminar su cuenta de app o servicio gratuito en los últimos 3 meses',
    'PC_IND_IUACRG': 'Porcentaje de individuos que han abierto cuenta con app o servicio gratuito',
    'PC_IND_IUOANY': 'Porcentaje de individuos que han usado internet en los últimos 3 meses para actividades de aprendizaje online',
    'pc_ind_igovanys': 'Porcentaje de individuos que han usado, en los últimos 12 meses, web o app de autoridades públicas',
    'pc_ind_igovrx': 'Porcentaje de individuos que no han solicitado, en los últimos 12 meses, documentos oficiales o certificados, beneficios o derechos, ni hicieron otras solicitudes, reclamaciones o quejas'
}

print("Leyendo archivo(s) de entrada...")
# Si hay varios CSVs con el mismo prefijo, se concatenan; si es uno solo, se lee directamente
archivos_entrada = sorted(carpeta.glob("EuroStatNUEVO*.csv"))
if not archivos_entrada:
    raise FileNotFoundError(f"No se encontraron archivos CSV con patrón 'EuroStatNUEVO*.csv' en {carpeta}")
df_entrada = pd.concat([pd.read_csv(f, encoding='utf-8-sig') for f in archivos_entrada], ignore_index=True)
print(f"Archivo(s) entrada: {len(df_entrada)} registros (de {len(archivos_entrada)} fichero(s))")

print("Transformando datos...")
df_transformado = pd.DataFrame({
    'Periodo': df_entrada['ExpPeriod'],
    'Pais': df_entrada['ExpCountry'],
    'Pais_Descripcion': df_entrada['ExpCountry'].map(dict_paises).fillna('País no disponible'),
    'Variable_Codigo': df_entrada['ExpVariable'],
    'Variable_Descripcion': df_entrada['ExpVariable'].map(dict_variables).fillna('Descripción no disponible'),
    'Desagregacion_Codigo': df_entrada['ExpBrkDwn'],
    'Desagregacion_Descripcion': df_entrada['ExpBrkDwn'].map(dict_desagregaciones).fillna('Descripción no disponible'),
    'Unidad_Codigo': df_entrada['ExpUnit'],
    'Unidad_Descripcion': df_entrada['ExpUnit'].map(dict_unidades).fillna('Descripción no disponible'),
    'Valor': df_entrada['Value']
})

print("Generando resúmenes...")
resumen_vars = df_transformado.groupby(['Variable_Codigo', 'Variable_Descripcion']).size().reset_index(name='Registros').sort_values('Variable_Codigo')
resumen_desag = df_transformado.groupby(['Desagregacion_Codigo', 'Desagregacion_Descripcion']).size().reset_index(name='Registros').sort_values('Desagregacion_Codigo')
resumen_unid = df_transformado.groupby(['Unidad_Codigo', 'Unidad_Descripcion']).size().reset_index(name='Registros').sort_values('Unidad_Codigo')
resumen_paises = df_transformado.groupby(['Pais', 'Pais_Descripcion']).size().reset_index(name='Registros').sort_values('Pais')

print(f"Guardando CSVs en: {carpeta_salida}")
# Datos transformados
archivo_datos = carpeta_salida / "EuroStatDESI_TRANSFORMADO2.csv"
df_transformado.to_csv(archivo_datos, index=False, encoding='utf-8-sig')

# Resúmenes (cada uno en su propio CSV)
resumen_vars.to_csv(carpeta_salida / 'EuroStatDESI_Resumen_Variables.csv', index=False, encoding='utf-8-sig')
resumen_desag.to_csv(carpeta_salida / 'EuroStatDESI_Resumen_Desagregaciones.csv', index=False, encoding='utf-8-sig')
resumen_unid.to_csv(carpeta_salida / 'EuroStatDESI_Resumen_Unidades.csv', index=False, encoding='utf-8-sig')
resumen_paises.to_csv(carpeta_salida / 'EuroStatDESI_Resumen_Paises.csv', index=False, encoding='utf-8-sig')

# Mostrar elementos sin traducir
sin_traducir_vars = df_transformado[df_transformado['Variable_Descripcion'] == 'Descripción no disponible']['Variable_Codigo'].unique()
sin_traducir_desag = df_transformado[df_transformado['Desagregacion_Descripcion'] == 'Descripción no disponible']['Desagregacion_Codigo'].unique()
sin_traducir_unid = df_transformado[df_transformado['Unidad_Descripcion'] == 'Descripción no disponible']['Unidad_Codigo'].unique()

print(f"\n=== COMPLETADO ===")
print(f"Total registros: {len(df_transformado)}")
print(f"Total países: {resumen_paises['Pais'].nunique()}")

if len(sin_traducir_vars) > 0:
    print(f"\n⚠️ Variables sin traducir ({len(sin_traducir_vars)}): {list(sin_traducir_vars)}")
if len(sin_traducir_desag) > 0:
    print(f"\n⚠️ Desagregaciones sin traducir ({len(sin_traducir_desag)}): {list(sin_traducir_desag)}")
if len(sin_traducir_unid) > 0:
    print(f"\n⚠️ Unidades sin traducir ({len(sin_traducir_unid)}): {list(sin_traducir_unid)}")

if len(sin_traducir_vars) == 0 and len(sin_traducir_desag) == 0 and len(sin_traducir_unid) == 0:
    print("\n✅ Todas las descripciones han sido traducidas correctamente")